### ISSUE TITLE
Generate ytop-chart/templates/ytsaurus-crd.yaml

### ISSUE THREAD

**Issue by ernado** [go-faster/yt-k8s-operator#7]

**Comment by ghost** [comment]
Done in https://github.com/go-faster/yt-k8s-operator/commit/ffe9c0128e803a3117a301c0a7f370521aaa68b4 and https://github.com/go-faster/yt-k8s-operator/commit/2127793e65b36f95748a868a3e9cfc8bc8148e3b.
